apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "epha-operator.fullname" . }}-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "epha-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "epha-operator.fullname" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io